data_sources:
  - name: sales_slice_data
    path: "oci://your_bucket/your_namespace/your_csv_data.csv"
    format: "csv"
    options:
      header: "true"
      inferSchema: "true"
    preprocessing_sql: |
      SELECT 
          CustomerID, 
          Quantity*10 NewQuantity
      FROM sales_slice_data_stg
    target_table: "lake.bronze.sales_slicev3"
